name: 'PR Dependencies List'
description: 'Create the PR Dependencies list and update PRs in stack'
inputs:
  github_token:
    description: 'Token to use for authenticated GitHub API requests'
    required: false
    default: ${{ github.token }}
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
